// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvL9EetEZYZ5Z--94xJZr0B45Vl1hY-To',
    appId: '1:357443021886:web:016fd5fb6695e77c6af56f',
    messagingSenderId: '357443021886',
    projectId: 'apptarefa-91280',
    authDomain: 'apptarefa-91280.firebaseapp.com',
    storageBucket: 'apptarefa-91280.firebasestorage.app',
    measurementId: 'G-XJ12Y3LZQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi7xFGwWxK7SZtU5APLXx5mMiwzEi0fsk',
    appId: '1:357443021886:android:bd3d20f4f96f67576af56f',
    messagingSenderId: '357443021886',
    projectId: 'apptarefa-91280',
    storageBucket: 'apptarefa-91280.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvL9EetEZYZ5Z--94xJZr0B45Vl1hY-To',
    appId: '1:357443021886:web:598c94180331ece96af56f',
    messagingSenderId: '357443021886',
    projectId: 'apptarefa-91280',
    authDomain: 'apptarefa-91280.firebaseapp.com',
    storageBucket: 'apptarefa-91280.firebasestorage.app',
    measurementId: 'G-3WCJKDMESB',
  );
}
